# Generated by Django 5.2.4 on 2025-07-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('password', models.BinaryField(max_length=8)),
                ('e_mail', models.EmailField(max_length=200)),
            ],
        ),
    ]
